eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8080
spring:
  application:
    name: zuul-server
zuul:
  routes:
    client1:
      path: /client1
      service-id: eureka-client-1
    client2:
      path: /client2
      service-id: eureka-client-2